package com.rozetkapay.demo.presentation.theme

import androidx.compose.ui.graphics.Color

object RozetkaPayDemoAppColors {

    // light
    val primaryLight = Color(0xFF35693E)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFB7F1BA)
    val onPrimaryContainerLight = Color(0xFF002109)
    val secondaryLight = Color(0xFF516351)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFD4E8D1)
    val onSecondaryContainerLight = Color(0xFF0F1F11)
    val tertiaryLight = Color(0xFF39656D)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFBDEAF3)
    val onTertiaryContainerLight = Color(0xFF001F24)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF410002)
    val backgroundLight = Color(0xFFF7FBF2)
    val onBackgroundLight = Color(0xFF181D18)
    val surfaceLight = Color(0xFFF7FBF2)
    val onSurfaceLight = Color(0xFF181D18)
    val surfaceVariantLight = Color(0xFFDDE5D9)
    val onSurfaceVariantLight = Color(0xFF414941)
    val outlineLight = Color(0xFF727970)
    val outlineVariantLight = Color(0xFFC1C9BE)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF2D322C)
    val inverseOnSurfaceLight = Color(0xFFEEF2EA)
    val inversePrimaryLight = Color(0xFF9CD4A0)
    val surfaceDimLight = Color(0xFFD7DBD3)
    val surfaceBrightLight = Color(0xFFF7FBF2)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF1F5EC)
    val surfaceContainerLight = Color(0xFFEBEFE7)
    val surfaceContainerHighLight = Color(0xFFE5E9E1)
    val surfaceContainerHighestLight = Color(0xFFE0E4DB)

    // dark
    val primaryDark = Color(0xFF9CD4A0)
    val onPrimaryDark = Color(0xFF003914)
    val primaryContainerDark = Color(0xFF1C5129)
    val onPrimaryContainerDark = Color(0xFFB7F1BA)
    val secondaryDark = Color(0xFFB8CCB6)
    val onSecondaryDark = Color(0xFF243425)
    val secondaryContainerDark = Color(0xFF3A4B3A)
    val onSecondaryContainerDark = Color(0xFFD4E8D1)
    val tertiaryDark = Color(0xFFA1CED7)
    val onTertiaryDark = Color(0xFF00363D)
    val tertiaryContainerDark = Color(0xFF1F4D54)
    val onTertiaryContainerDark = Color(0xFFBDEAF3)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF101510)
    val onBackgroundDark = Color(0xFFE0E4DB)
    val surfaceDark = Color(0xFF101510)
    val onSurfaceDark = Color(0xFFE0E4DB)
    val surfaceVariantDark = Color(0xFF414941)
    val onSurfaceVariantDark = Color(0xFFC1C9BE)
    val outlineDark = Color(0xFF8B9389)
    val outlineVariantDark = Color(0xFF414941)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFE0E4DB)
    val inverseOnSurfaceDark = Color(0xFF2D322C)
    val inversePrimaryDark = Color(0xFF35693E)
    val surfaceDimDark = Color(0xFF101510)
    val surfaceBrightDark = Color(0xFF363A35)
    val surfaceContainerLowestDark = Color(0xFF0B0F0B)
    val surfaceContainerLowDark = Color(0xFF181D18)
    val surfaceContainerDark = Color(0xFF1C211C)
    val surfaceContainerHighDark = Color(0xFF262B26)
    val surfaceContainerHighestDark = Color(0xFF313630)
}

object RozetkaPayDemoAppClassicColors {

    // light
    val primaryLight = Color(0xFF00687B)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFAEECFF)
    val onPrimaryContainerLight = Color(0xFF001F26)
    val secondaryLight = Color(0xFF00687A)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFADECFF)
    val onSecondaryContainerLight = Color(0xFF001F26)
    val tertiaryLight = Color(0xFF575C7E)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFDEE1FF)
    val onTertiaryContainerLight = Color(0xFF141937)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF410002)
    val backgroundLight = Color(0xFFF5FAFC)
    val onBackgroundLight = Color(0xFF171C1E)
    val surfaceLight = Color(0xFFF5FAFC)
    val onSurfaceLight = Color(0xFF171C1E)
    val surfaceVariantLight = Color(0xFFDBE4E7)
    val onSurfaceVariantLight = Color(0xFF3F484B)
    val outlineLight = Color(0xFF70797C)
    val outlineVariantLight = Color(0xFFBFC8CB)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF2C3133)
    val inverseOnSurfaceLight = Color(0xFFECF2F4)
    val inversePrimaryLight = Color(0xFF85D2E7)
    val surfaceDimLight = Color(0xFFD5DBDD)
    val surfaceBrightLight = Color(0xFFF5FAFC)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFEFF4F7)
    val surfaceContainerLight = Color(0xFFE9EFF1)
    val surfaceContainerHighLight = Color(0xFFE4E9EB)
    val surfaceContainerHighestLight = Color(0xFFDEE3E6)

    // dark
    val primaryDark = Color(0xFF85D2E7)
    val onPrimaryDark = Color(0xFF003641)
    val primaryContainerDark = Color(0xFF004E5D)
    val onPrimaryContainerDark = Color(0xFFAEECFF)
    val secondaryDark = Color(0xFF85D2E7)
    val onSecondaryDark = Color(0xFF003641)
    val secondaryContainerDark = Color(0xFF004E5D)
    val onSecondaryContainerDark = Color(0xFFADECFF)
    val tertiaryDark = Color(0xFFBFC4EB)
    val onTertiaryDark = Color(0xFF292E4D)
    val tertiaryContainerDark = Color(0xFF3F4565)
    val onTertiaryContainerDark = Color(0xFFDEE1FF)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF0F1416)
    val onBackgroundDark = Color(0xFFDEE3E6)
    val surfaceDark = Color(0xFF0F1416)
    val onSurfaceDark = Color(0xFFDEE3E6)
    val surfaceVariantDark = Color(0xFF3F484B)
    val onSurfaceVariantDark = Color(0xFFBFC8CB)
    val outlineDark = Color(0xFF899295)
    val outlineVariantDark = Color(0xFF3F484B)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFDEE3E6)
    val inverseOnSurfaceDark = Color(0xFF2C3133)
    val inversePrimaryDark = Color(0xFF00687B)
    val surfaceDimDark = Color(0xFF0F1416)
    val surfaceBrightDark = Color(0xFF343A3C)
    val surfaceContainerLowestDark = Color(0xFF090F11)
    val surfaceContainerLowDark = Color(0xFF171C1E)
    val surfaceContainerDark = Color(0xFF1B2022)
    val surfaceContainerHighDark = Color(0xFF252B2D)
    val surfaceContainerHighestDark = Color(0xFF303638)
}