package com.rozetkapay.demo.presentation.theme

import androidx.compose.ui.graphics.Color

object RozetkaPayDemoAppColors {

    // Light
    val primaryLight = Color(0xFF006E2E)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFF27C25D)
    val onPrimaryContainerLight = Color(0xFF00250B)
    val secondaryLight = Color(0xFF326A3D)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFB6F4BB)
    val onSecondaryContainerLight = Color(0xFF1B542A)
    val tertiaryLight = Color(0xFF0C5CBB)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFF79A8FF)
    val onTertiaryContainerLight = Color(0xFF001C44)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF410002)
    val backgroundLight = Color(0xFFF3FCEF)
    val onBackgroundLight = Color(0xFF161D16)
    val surfaceLight = Color(0xFFF3FCEF)
    val onSurfaceLight = Color(0xFF161D16)
    val surfaceVariantLight = Color(0xFFD8E7D5)
    val onSurfaceVariantLight = Color(0xFF3D4A3D)
    val outlineLight = Color(0xFF6D7B6C)
    val outlineVariantLight = Color(0xFFBCCBB9)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF2B322A)
    val inverseOnSurfaceLight = Color(0xFFEBF3E7)
    val inversePrimaryLight = Color(0xFF4FE177)

    // Dark
    val primaryDark = Color(0xFF4FE177)
    val onPrimaryDark = Color(0xFF003915)
    val primaryContainerDark = Color(0xFF00AB4D)
    val onPrimaryContainerDark = Color(0xFF000000)
    val secondaryDark = Color(0xFF98D59E)
    val onSecondaryDark = Color(0xFF003915)
    val secondaryContainerDark = Color(0xFF104B22)
    val onSecondaryContainerDark = Color(0xFFA9E6AE)
    val tertiaryDark = Color(0xFFACC7FF)
    val onTertiaryDark = Color(0xFF002F67)
    val tertiaryContainerDark = Color(0xFF5B94F7)
    val onTertiaryContainerDark = Color(0xFF000000)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF0E150E)
    val onBackgroundDark = Color(0xFFDCE5D9)
    val surfaceDark = Color(0xFF0E150E)
    val onSurfaceDark = Color(0xFFDCE5D9)
    val surfaceVariantDark = Color(0xFF3D4A3D)
    val onSurfaceVariantDark = Color(0xFFBCCBB9)
    val outlineDark = Color(0xFF869585)
    val outlineVariantDark = Color(0xFF3D4A3D)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFDCE5D9)
    val inverseOnSurfaceDark = Color(0xFF2B322A)
    val inversePrimaryDark = Color(0xFF006E2E)
}

object RozetkaPayDemoAppClassicColors {

    // light
    val primaryLight = Color(0xFF00687B)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFAEECFF)
    val onPrimaryContainerLight = Color(0xFF001F26)
    val secondaryLight = Color(0xFF4B6269)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFCEE7EF)
    val onSecondaryContainerLight = Color(0xFF061F25)
    val tertiaryLight = Color(0xFF575C7E)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFDEE0FF)
    val onTertiaryContainerLight = Color(0xFF141937)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF410002)
    val backgroundLight = Color(0xFFF5FAFC)
    val onBackgroundLight = Color(0xFF171C1E)
    val surfaceLight = Color(0xFFF5FAFC)
    val onSurfaceLight = Color(0xFF171C1E)
    val surfaceVariantLight = Color(0xFFDBE4E7)
    val onSurfaceVariantLight = Color(0xFF3F484B)
    val outlineLight = Color(0xFF70787C)
    val outlineVariantLight = Color(0xFFBFC8CB)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF2C3133)
    val inverseOnSurfaceLight = Color(0xFFECF2F4)
    val inversePrimaryLight = Color(0xFF85D2E8)
    val surfaceDimLight = Color(0xFFD5DBDD)
    val surfaceBrightLight = Color(0xFFF5FAFC)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFEFF4F7)
    val surfaceContainerLight = Color(0xFFE9EFF1)
    val surfaceContainerHighLight = Color(0xFFE4E9EB)
    val surfaceContainerHighestLight = Color(0xFFDEE3E6)

    // dark
    val primaryDark = Color(0xFF85D2E8)
    val onPrimaryDark = Color(0xFF003641)
    val primaryContainerDark = Color(0xFF004E5D)
    val onPrimaryContainerDark = Color(0xFFAEECFF)
    val secondaryDark = Color(0xFFB2CBD3)
    val onSecondaryDark = Color(0xFF1D343A)
    val secondaryContainerDark = Color(0xFF344A51)
    val onSecondaryContainerDark = Color(0xFFCEE7EF)
    val tertiaryDark = Color(0xFFBFC4EB)
    val onTertiaryDark = Color(0xFF292E4D)
    val tertiaryContainerDark = Color(0xFF3F4565)
    val onTertiaryContainerDark = Color(0xFFDEE0FF)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF0F1416)
    val onBackgroundDark = Color(0xFFDEE3E6)
    val surfaceDark = Color(0xFF0F1416)
    val onSurfaceDark = Color(0xFFDEE3E6)
    val surfaceVariantDark = Color(0xFF3F484B)
    val onSurfaceVariantDark = Color(0xFFBFC8CB)
    val outlineDark = Color(0xFF899295)
    val outlineVariantDark = Color(0xFF3F484B)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFDEE3E6)
    val inverseOnSurfaceDark = Color(0xFF2C3133)
    val inversePrimaryDark = Color(0xFF00687B)
    val surfaceDimDark = Color(0xFF0F1416)
    val surfaceBrightDark = Color(0xFF343A3C)
    val surfaceContainerLowestDark = Color(0xFF090F11)
    val surfaceContainerLowDark = Color(0xFF171C1E)
    val surfaceContainerDark = Color(0xFF1B2022)
    val surfaceContainerHighDark = Color(0xFF252B2D)
    val surfaceContainerHighestDark = Color(0xFF303638)
}
