package com.rozetkapay.demo.presentation.theme

import androidx.compose.ui.graphics.Color

object RozetkaPayDemoAppColors {

    // Light
    val primaryLight = Color(0xFF006E2E)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFF27C25D)
    val onPrimaryContainerLight = Color(0xFF00250B)
    val secondaryLight = Color(0xFF326A3D)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFB6F4BB)
    val onSecondaryContainerLight = Color(0xFF1B542A)
    val tertiaryLight = Color(0xFF0C5CBB)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFF79A8FF)
    val onTertiaryContainerLight = Color(0xFF001C44)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF410002)
    val backgroundLight = Color(0xFFF3FCEF)
    val onBackgroundLight = Color(0xFF161D16)
    val surfaceLight = Color(0xFFF3FCEF)
    val onSurfaceLight = Color(0xFF161D16)
    val surfaceVariantLight = Color(0xFFD8E7D5)
    val onSurfaceVariantLight = Color(0xFF3D4A3D)
    val outlineLight = Color(0xFF6D7B6C)
    val outlineVariantLight = Color(0xFFBCCBB9)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF2B322A)
    val inverseOnSurfaceLight = Color(0xFFEBF3E7)
    val inversePrimaryLight = Color(0xFF4FE177)

    // Dark
    val primaryDark = Color(0xFF4FE177)
    val onPrimaryDark = Color(0xFF003915)
    val primaryContainerDark = Color(0xFF00AB4D)
    val onPrimaryContainerDark = Color(0xFF000000)
    val secondaryDark = Color(0xFF98D59E)
    val onSecondaryDark = Color(0xFF003915)
    val secondaryContainerDark = Color(0xFF104B22)
    val onSecondaryContainerDark = Color(0xFFA9E6AE)
    val tertiaryDark = Color(0xFFACC7FF)
    val onTertiaryDark = Color(0xFF002F67)
    val tertiaryContainerDark = Color(0xFF5B94F7)
    val onTertiaryContainerDark = Color(0xFF000000)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF0E150E)
    val onBackgroundDark = Color(0xFFDCE5D9)
    val surfaceDark = Color(0xFF0E150E)
    val onSurfaceDark = Color(0xFFDCE5D9)
    val surfaceVariantDark = Color(0xFF3D4A3D)
    val onSurfaceVariantDark = Color(0xFFBCCBB9)
    val outlineDark = Color(0xFF869585)
    val outlineVariantDark = Color(0xFF3D4A3D)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFDCE5D9)
    val inverseOnSurfaceDark = Color(0xFF2B322A)
    val inversePrimaryDark = Color(0xFF006E2E)
}